version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - .dockervenv:/app/.venv
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    working_dir: /app
    entrypoint: tail -f /dev/null
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
