version: "3"
services:
  app:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: tail -f /dev/null
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}